root: true
env:
    browser: true
    es2021: true
    node: true
extends: ["eslint:recommended"]
parser: "@babel/eslint-parser"
# requireConfigFile: false
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: latest
    sourceType: module
plugins:
    - "@babel"
    - react
rules:
    indent:
        - warn
        - 4
    linebreak-style:
        - warn
        - windows
    quotes:
        - error
        - double
    semi:
        - error
        - always
    no-unused-vars: 0
