language: node_js
node_js:
    - stable
cache:
    directories:
        - node_modules
script:
    - npm run build
deploy:
    provider: heroku
    app: marvel-for-noobs-121
    api_key:
        secure: HEILtfgm6BaeYzGr5PXAai0leAjWimVPkV587O1LrrgCp+UTEDE7Vf1iNkmLLPjPenpPLpsxwUGaiN4AHUhD4WVIwlP+VxpB4+ZHaRjvQoaT85M8xwLt2FHWPBdAYWVD1XDRPVXuVLW1BaAO3t2DIdfgQB92NgruAgFx70rDWyFD//JFtjIkcxZqI0yardPxuDfIS8bEHCXrqLBwuXKKak8hrei8XKQ6au8bv8y9Uwo+z4Nz7w/JcUnrF/mRlQJEri3nwRR8LxSDWUshSXUjC5GWQ5INjuJVz6oN4nz+UsSZdbKciAcVhE+m4jBiQ979s0ZRHeTqenjSVLxZxyS18Qky002wZxFVoS2W3LalqeE0AjOGs5HAvMqNgvFqiWhHUtiWp8SntZ0ufsqaUmLahp8bXNSU5n/wdj4PdfhmZH0FxowrkmAWmJA4+fPl5jiZ4R/KR0QBWxuSSy8imibDCibIBQncLL68Nr2UgqnhaA0gHxjPUU7c24TYhBbo8KmMf9h/eYXz/TKgWbYC2gzx4TqhuZ6zFZAqhDZV9hvTgJfpAkj9HC13hkbOYPPqBfFTLsDl/T60Rp1lbWL6IJ0R1YNPV3OzwBuL7aB8xDJs9JtBwdl+FB2vZD3FA/xvK1dUluC0dQKZjYC4G/Q7dcG53wRWdfwzU7fK9J3OIhsbSjQ=
